on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Daily 0000 UTC
  workflow_dispatch:

name: linting

# This limits the workflow to 1 active run at any given time for a specific branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ETHERSCAN_TOKEN: 9MKURTHE8FNA9NRUUJBHMUEVY6IQ5K1EGY
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WEB3_INFURA_PROJECT_ID: 44c6300c5e5b4b2da5fc42b06bf18a8e

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheel with mypycify
        id: wheel
        uses: BobTheBuidler/mypycify@v0.0.1
        with:
          python-version: "3.13"
          hash-key: |
            brownie/**/*.py
            pyproject.toml
            setup.py
            requirements.txt
          ccache: true
          pip-cache-dependency-path: |
            pyproject.toml
            setup.py
            requirements.txt
            requirements-dev.txt
            requirements-windows.txt

  linting:
    needs: build-wheel
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        job: [lint, docs-local]
        experimental: [false]
        include:
          - job: docs-external
            experimental: true

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: pip
        cache-dependency-path: |
          pyproject.toml
          setup.py
          requirements.in
          requirements.txt
          requirements-windows.in
          requirements-windows.txt
          requirements-dev.in
          requirements-dev.txt

    - name: Cache .mypy_cache
      uses: actions/cache@v4
      with:
        path: .mypy_cache
        key: mypy-cache-${{ runner.os }}-${{ hashFiles('**/*.py', 'pyproject.toml') }}

    - name: Install Tox
      run: pip install tox

    - name: Cache tox environment
      uses: actions/cache@v4
      with:
        path: .tox
        key: ${{ runner.os }}-${{ matrix.job }}-3.13-${{ matrix.architecture }}-${{ hashFiles('pyproject.toml', 'setup.py', 'requirements.in', 'requirements.txt', 'requirements-windows.in', 'requirements-windows.txt', 'requirements-dev.in', 'requirements-dev.txt', 'tox.ini') }}

    # Download the wheel artifact built by mypycify
    - name: Download wheel
      uses: actions/download-artifact@v4
      with:
        path: .
        pattern: BobTheBuidler_mypycified_wheel-Linux-py3.13-${{ steps.wheel.outputs.artifact-name }}

    - name: Run Tox
      env:
          CC: ccache gcc
      run: tox -e ${{ matrix.job }}
      continue-on-error: ${{ matrix.experimental }}
